### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by bhbr**
converted from ObjC to Swift

### CODE REVIEW

**Comment by bhbr** [comment]
Sorry, wrong button. I converted TurtleBezierPath to Swift in my fork (republished with MIT licence and copyright notice).

**Comment by mindbrix** [comment]
No problems. I had been thinking about doing this myself ;-)

How have you been using TurtleBezierPath?

**Comment by bhbr** [comment]
As part of CYRKeyboardButton, which I am extending right now to support images on buttons. It draws the buttons and longpress submenus with TurtleBezierPath. The goal is a math keyboard extension.

**Comment by mindbrix** [comment]
Nice. Thanks.

**Pull request closed without merging**
